name: Clean the logs of the run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_run: 
    workflows: [Check the pull requests]
    types:
      - completed
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

permissions:
  actions: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.FLAG }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install required dependencies
        run: npm install
      - name: Run the tests
        run: npm test
        env:
         FLAG: ${{ secrets.FLAG }}    

  # This workflow contains a single job called "build"
  clean:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.deleteWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            })
